services:
  - type: web
    name: todolist
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todolist.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"